repos:
-   repo: local
    hooks:
      - id: requirements
        name: Atualizar requirements a partir do venv
        language: system
        pass_filenames: false
        stages: [pre-commit]
        entry: powershell -NoProfile -Command ". .\.venv\Scripts\Activate.ps1; pip freeze > requirements.txt"
